<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-01-10T22:30:00 IST" name="TestSuite" finished-at="2020-01-10T22:30:47 IST" duration-ms="46870">
    <groups>
      <group name="Regression">
        <method signature="LoginAdmin.AdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" name="AdminLogin" class="com.hrms.testcase.admin.LoginAdmin"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="LoginAdmin.AdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" name="AdminLogin" class="com.hrms.testcase.admin.LoginAdmin"/>
        <method signature="LoginAdmin.FalseAdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" name="FalseAdminLogin" class="com.hrms.testcase.admin.LoginAdmin"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2020-01-10T22:30:00 IST" name="testng" finished-at="2020-01-10T22:30:47 IST" duration-ms="46870">
      <class name="com.hrms.testcase.admin.LoginAdmin">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:00 IST" name="setup" finished-at="2020-01-10T22:30:00 IST" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="AdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:00 IST" name="AdminLogin" finished-at="2020-01-10T22:30:21 IST" duration-ms="20699" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdminLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:21 IST" name="closeBrowser" finished-at="2020-01-10T22:30:21 IST" duration-ms="435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method retried="true" signature="FalseAdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:21 IST" name="FalseAdminLogin" finished-at="2020-01-10T22:30:28 IST" duration-ms="6616" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost/erms/erms/admin/] but found [http://localhost/erms/erms/admin/welcome.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost/erms/erms/admin/] but found [http://localhost/erms/erms/admin/welcome.php]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.hrms.testcase.admin.LoginAdmin.FalseAdminLogin(LoginAdmin.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FalseAdminLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:28 IST" name="closeBrowser" finished-at="2020-01-10T22:30:28 IST" duration-ms="536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method signature="FalseAdminLogin()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:28 IST" name="FalseAdminLogin" finished-at="2020-01-10T22:30:44 IST" duration-ms="15450" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://localhost/erms/erms/admin/] but found [http://localhost/erms/erms/admin/welcome.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://localhost/erms/erms/admin/] but found [http://localhost/erms/erms/admin/welcome.php]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.hrms.testcase.admin.LoginAdmin.FalseAdminLogin(LoginAdmin.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FalseAdminLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.hrms.testcase.admin.LoginAdmin@76f2bbc1]" started-at="2020-01-10T22:30:46 IST" name="closeBrowser" finished-at="2020-01-10T22:30:47 IST" duration-ms="676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.hrms.testcase.admin.LoginAdmin -->
    </test> <!-- testng -->
  </suite> <!-- TestSuite -->
</testng-results>
